---
title: "thesis_data_analysis"
author: "Luis Luarte"
date: '2022-08-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libs

```{r}
pacman::p_load(
  tidyverse,
  ggplot2,
  rstudioapi,
  devtools,
  lme4,
  lmerTest,
  googledrive,
  ggpubr,
  cowplot,
  sjPlot,
  ggsignif
)

# source lickometer library
devtools::source_url("https://github.com/lab-cpl/lickometer-library/blob/main/src/lickometer_functions_compilate.R?raw=TRUE")

```

# Load data sets

POOL 1, POOl 2

```{r}
# # this data is in a different format because it was done in a previous
# # version of the lickometer
# # change col names before merging both pools
# data_pool1 <- readRDS('../data/objective_2_pool_1.RDS')
# 
# data_pool1 <- data_pool1 %>%
#   filter(
#     complete_data == TRUE,
#     start <= pcTime &
#         pcTime <= end,
#     n_sesion != 29
#   ) %>%
#   mutate(
#     actividad = licksCum,
#     sensor = as.factor(if_else(spoutNumber == "RIGHT", 1, 0)),
#     tiempo = msFromStart,
#     evento = eventsCum,
#     exito = as.factor(rewardsCum),
#     fecha = date,
#     exp_phase = if_else(exp_phase == "BASAL", "basal", "experimental"),
#     exp_group = if_else(exp_group == "CONTROL", "control", "experimental"),
#     tipo_recompensa = if_else(is_random == FALSE, "sacarosa", "sacarosar"),
#     pool = "pool_1"
#   ) %>%
#   select(
#     fecha, ID, sensor, tiempo, actividad, evento, exito, tipo_recompensa, pool, n_sesion, exp_phase, exp_group
#   )
# 
# data_pool2 <- load_experiment(
#   '../data/meta/lickometer_metadata.csv',
#   '../data/raw/pool_2'
# )
# saveRDS(data_pool2, '../data/objective_2_pool_2.RDS')
# data_pool2 <- readRDS('../data/objective_2_pool_2.RDS') %>%
#   select(
#     fecha, ID, sensor, tiempo, actividad, evento, exito, tipo_recompensa, pool, n_sesion
#   ) %>%
#   mutate(
#     n_sesion = as.numeric(as.character(n_sesion)),
#     exp_phase = if_else(as.numeric(n_sesion) > 12, "experimental", "basal"),
#     exp_group = if_else(ID %in% c(393, 394, 398, 400), "experimental", "control")
#     )
# 
# objective_2_data <- bind_rows(data_pool1, data_pool2)
# saveRDS(objective_2_data, '../data/objective_2_complete.RDS')
objective_2_data <- readRDS('../data/objective_2_complete.RDS')
objective_2_data <- objective_2_data %>% 
  group_by(ID, n_sesion, sensor) %>% 
  # correct 'actividad' , 'evento' , 'exito'
  mutate(
    actividad = actividad - actividad[1],
    evento = evento - evento[1],
    exito = as.numeric(exito),
    exito = exito - exito[1],
    evento_bin = evento - lag(evento, default = 0),
    actividad_bin = actividad - lag(actividad, default = 0),
    exito_bin = exito - lag(exito, default = 0)
  ) %>%
  ungroup()
```

# mean total difference with baseline

```{r}
# add a column with mean baseline licks per spout
baseline_total <- objective_2_data %>% 
  filter(n_sesion <= 12, n_sesion >= 7) %>% 
  group_by(
    ID,
    n_sesion
  ) %>% 
  summarise(
    evento_basal_ = sum(evento_bin),
    actividad_basal_ = n()
  ) %>% 
  ungroup() %>% 
  group_by(
    ID
  ) %>%
  summarise(
    evento_basal = mean(evento_basal_),
    actividad_basal = mean(actividad_basal_)
  ) %>% 
  ungroup()

# add baseline
df_summ_total <- objective_2_data %>% 
  group_by(
    n_sesion,
    ID,
    pool,
    exp_group,
    exp_phase
  ) %>% 
  summarise(
    actividad_summ = n(),
    evento_summ = sum(evento_bin),
    exito_summ = sum(exito_bin)
  ) %>% 
  ungroup() %>% 
  left_join(baseline_total, by = c("ID")) %>% 
  mutate(
    evento_delta = ((evento_summ - evento_basal) / evento_basal) * 100,
    actividad_delta = ((actividad_summ - actividad_basal) / actividad_basal) * 100
  ) %>% 
  ungroup()

# mean differences
df_summ_m_total <- df_summ_total %>%
  group_by(
    exp_phase,
    exp_group,
    n_sesion,
  ) %>% 
  summarise(
    evento_delta_m = mean(evento_delta),
    actividad_delta_m = mean(actividad_delta)
  ) %>% 
  ungroup()

# licks
total_activity_licks <- lmer(
  data = df_summ_total,
  actividad_summ ~ exp_group * exp_phase * n_sesion + actividad_basal + (1 | ID)+ (1 | pool)
)
summary(total_activity_licks)

total_activity_df <- plot_model(total_activity_licks, type = "int")[[1]]$data %>% as_tibble()

# events
total_events_licks <- lmer(
  data = df_summ_total,
  evento_summ ~ exp_group * exp_phase + evento_basal + (1 | ID)+ (1 | pool)
)
summary(total_events_licks)

total_events_df <- plot_model(total_events_licks, type = "int")$data %>% as_tibble()

# total_activity_licks <- lmer(
#   data = df_summ_total %>% filter(exp_phase == "experimental"),
#   actividad_delta ~ exp_group + (1 | ID/pool)
# )
# summary(total_activity_licks)


group_m <- df_summ_m_total %>% 
  filter(exp_phase == "experimental") %>% 
  group_by(exp_group, exp_phase) %>% 
  summarise(
    m = mean(actividad_delta_m),
    s = sd(actividad_delta_m) / sqrt(n())
    )

p1 <- group_m %>% 
  ggplot(aes(exp_group, m,
             ymin = m - s, ymax = m + s,
             fill = exp_group, color = exp_group)) +
  geom_col(width = 0.5) +
  geom_errorbar(width = 0.3) +
  geom_hline(yintercept = 0, color = "gray") +
  scale_fill_manual(values = c("black", "#56B4E9")) +
  scale_color_manual(values = c("black", "#56B4E9")) +
  scale_x_discrete(labels = c("Control", "Uncertainty")) +
  theme_pubr() +
  xlab("") +
  ylab("%Δ Total number of licks") +
  theme(
    legend.position = "none"
  )
ggsave("../images/extra1.png", p1, width = 6, height = 4)

p2 <- total_activity_df %>% 
  mutate(x = if_else(x == 1, "Basal", "Uncertainty")) %>% 
  ggplot(aes(group, predicted, fill = x, color = x)) +
  geom_col(position = "dodge2") +
  geom_errorbar(aes(
    ymin = conf.low, ymax = conf.high
  ), position = position_dodge(0.9), width = 0.3) +
  scale_fill_manual(values = c("black", "#56B4E9")) +
  scale_color_manual(values = c("black", "#56B4E9")) +
  theme_pubr() +
  ylab("Number of licks estimates") +
  xlab("") +
  scale_x_discrete(labels = c("Control", "Uncertainty")) +
  labs(fill = "Experimental phase", color = "Experimental phase") + 
  geom_signif(
    y_position = c(1500, 1500), xmin = c(0.8, 1.8), xmax = c(1.2, 2.2),
    annotation = c("NS", "**"), tip_length = 0
  )
ggsave("../images/extra2.png", p2, width = 6, height = 4)

p3 <- total_events_df %>% 
  mutate(x = if_else(x == 1, "Basal", "Uncertainty")) %>% 
  ggplot(aes(group, predicted, fill = x, color = x)) +
  geom_col(position = "dodge2") +
  geom_errorbar(aes(
    ymin = conf.low, ymax = conf.high
  ), position = position_dodge(0.9), width = 0.3) +
  scale_fill_manual(values = c("black", "#56B4E9")) +
  scale_color_manual(values = c("black", "#56B4E9")) +
  theme_pubr() +
  ylab("Number of events estimates") +
  xlab("") +
  scale_x_discrete(labels = c("Control", "Uncertainty")) +
  labs(fill = "Experimental phase", color = "Experimental phase") + 
  geom_signif(
    y_position = c(80, 80), xmin = c(0.8, 1.8), xmax = c(1.2, 2.2),
    annotation = c("NS", "**"), tip_length = 0
  )
ggsave("../images/extra3.png", p3, width = 6, height = 4)
```

# mean difference with basaline per spout

```{r}

reward_comparison <- objective_2_data %>% 
  filter(exp_group == "experimental", exp_phase == "experimental") %>% 
  group_by(tipo_recompensa, n_sesion, ID) %>% 
  summarise(l = n()) %>%
  ungroup() %>% 
  group_by(tipo_recompensa, n_sesion) %>% 
  summarise(licks = mean(l)) %>% 
  ungroup() %>% 
  group_by(tipo_recompensa) %>%
  summarise(m = mean(licks), s = sd(licks)/sqrt(n())) %>% 
  ungroup()

reward_comparison_mdl <- objective_2_data %>% 
  filter(exp_group == "experimental", exp_phase == "experimental") %>% 
  group_by(tipo_recompensa, n_sesion, ID) %>% 
  summarise(l = n())

reward_mdl <- lmer(
  data = reward_comparison_mdl,
  l ~ tipo_recompensa + (1 | ID)
)
summary(reward_mdl)

p4 <- reward_comparison %>% 
  ggplot(aes(tipo_recompensa, m,
             ymin = m - s, ymax = m + s,
             fill = tipo_recompensa, color = tipo_recompensa)) +
  geom_col(width = 0.5) +
  geom_errorbar(width = 0.3) +
  scale_fill_manual(values = c("black", "#56B4E9")) +
  scale_color_manual(values = c("black", "#56B4E9")) +
  scale_x_discrete(labels = c("Non-random", "Random")) +
  theme_pubr() +
  xlab("") +
  ylab("Total number of licks") +
  theme(
    legend.position = "none"
  ) +
  geom_signif(
    y_position = c(750), xmin = c(0.8), xmax = c(2.2),
    annotation = c("**"), tip_length = 0
  )
ggsave("../images/extra3.png", p4, width = 6, height = 4)

# add a column with mean baseline licks per spout
baseline <- objective_2_data %>% 
  filter(n_sesion <= 12, n_sesion >= 7) %>% 
  group_by(
    ID,
    n_sesion,
    sensor
  ) %>% 
  summarise(
    evento_b = sum(evento_bin),
    actividad_b = n()
  ) %>% 
  ungroup() %>% 
  group_by(
    ID,
    sensor
  ) %>% 
  summarise(
    evento_basal_ = mean(evento_b),
    actividad_basal_ = mean(actividad_b)
  ) %>% 
  ungroup() %>% 
  group_by(
    ID
  ) %>%
  summarise(
    evento_basal = mean(evento_basal_),
    actividad_basal = mean(actividad_basal_)
  ) %>% 
  ungroup()

mean_baseline <- baseline %>% 
  summarise(
    actividad_m = mean(actividad_basal),
    evento_m = mean(evento_basal)
  )

p5 <- reward_comparison %>% 
  ggplot(aes(tipo_recompensa, m,
             ymin = m - s, ymax = m + s,
             fill = tipo_recompensa, color = tipo_recompensa)) +
  geom_col(width = 0.5) +
  geom_errorbar(width = 0.3) +
  scale_fill_manual(values = c("black", "#56B4E9")) +
  scale_color_manual(values = c("black", "#56B4E9")) +
  scale_x_discrete(labels = c("Non-random", "Random")) +
  geom_hline(yintercept = mean_baseline$actividad_m, color = "gray") +
  geom_text(aes(2.45,mean_baseline$actividad_m,label = "E(Licks)", vjust = -1)) +
  theme_pubr() +
  xlab("") +
  ylab("Total number of licks") +
  theme(
    legend.position = "none"
  ) +
  geom_signif(
    y_position = c(750), xmin = c(0.8), xmax = c(2.2),
    annotation = c("**"), tip_length = 0
  )
ggsave("../images/extra4.png", p5, width = 6, height = 4)

# add baseline
df <- objective_2_data

# summary per ID per date
df_summ <- df %>% 
  group_by(
    n_sesion,
    ID,
    sensor,
    tipo_recompensa,
    pool,
    exp_group,
    exp_phase
  ) %>% 
  summarise(
    actividad_summ = n(),
    evento_summ = sum(evento_bin),
    exito_summ = sum(exito_bin)
  ) %>% 
  ungroup() %>% 
  left_join(baseline, by = c("ID")) %>% 
  mutate(
    evento_delta = ((evento_summ - evento_basal) / evento_basal) * 100,
    actividad_delta = ((actividad_summ - actividad_basal) / actividad_basal) * 100
  )

# mean differences
df_summ_m <- df_summ %>%
  group_by(
    exp_phase,
    exp_group,
    n_sesion,
    tipo_recompensa
  ) %>% 
  summarise(
    evento_delta_m = mean(evento_delta),
    actividad_delta_m = mean(actividad_delta)
  ) %>% 
  ungroup()

df_overall_m <- df_summ_m %>% 
  filter(exp_phase == "experimental", exp_group == "experimental") %>% 
  group_by(tipo_recompensa, exp_group, exp_phase) %>% 
  summarise(
    m = mean(actividad_delta_m),
    s = sd(actividad_delta_m) / sqrt(n())
    )
```

# stats pool 1

```{r}
# licks on each spout
data_pref <- data_pool1 %>% 
  filter(exp_group == "UNC", exp_phase == "EXPERIMENTAL") %>% 
  group_by(
    ID,
    n_sesion,
    is_random
  ) %>% 
  mutate(
     event_uncum = if_else(eventsCum - lag(eventsCum) > 0, 1, 0),
  ) %>% 
  summarise(
    licks = n(),
    events = sum(event_uncum, na.rm = TRUE)
  ) %>% 
  ungroup() %>% 
  pivot_wider(
    names_from = is_random,
    values_from = c("licks", "events")
  ) %>% 
  mutate(
    licks_diff = licks_FALSE - licks_TRUE,
    events_diff = events_FALSE - events_TRUE,
    licks_ratio = licks_FALSE / licks_TRUE,
    events_ratio = events_FALSE / events_TRUE
  )
  
# pref
pref_t <- t.test(data_pref$licks_FALSE, data_pref$licks_TRUE, paired = TRUE, alternative = "two.sided")

pref_mdl <- lmer(
  data = data_pref,
  licks_diff ~ (1 | ID)
)
summary(pref_mdl)

#total number of licks
data_mdl_1 <- data_pool1 %>% 
  filter(n_sesion < 29) %>% 
  group_by(
    exp_group,
    exp_phase,
    ID,
    n_sesion
    ) %>% 
  summarise(
    licks = n(),
    events = max(eventsCum),
    rewards = max(rewardsCum),
    lr = licks / rewards
  )

basal_licks <- data_mdl_1 %>% 
  filter(exp_phase == "BASAL") %>% 
  group_by(
    ID
  ) %>% 
  summarise(
    basal_licks = mean(licks),
    basal_events = mean(events),
    basal_lr = mean(lr)
  )

data_delta <- data_mdl_1 %>% 
  left_join(basal_licks) %>% 
  mutate(
    delta_licks = ((licks - basal_licks) / basal_licks) * 100,
    delta_events = ((events - basal_events) / basal_events) * 100,
    delta_lr = ((lr - basal_lr) / basal_lr) * 100,
  )

mdl_1 <- lmer(
  data = data_delta %>%  filter(exp_phase == "EXPERIMENTAL"),
  delta_licks ~ exp_group * n_sesion + (1 | ID)
)
summary(mdl_1)
confint(mdl_1)

mdl_2 <- lmer(
  data = data_delta %>%  filter(exp_phase == "EXPERIMENTAL"),
  delta_events ~ exp_group * n_sesion + (1 | ID)
)
summary(mdl_2)
confint(mdl_2)

data_mdl_1_m <- data_mdl_1 %>% 
  ungroup() %>% 
  group_by(
    exp_group,
    exp_phase,
    n_sesion
  ) %>% 
  summarise(
    m = mean(licks),
    s = sd(licks) / sqrt(n())
  )

data_mdl_1_m %>% 
  ggplot(aes(
    n_sesion,
    m,
    color = exp_group,
    ymax = m + s,
    ymin = m - s
  )) +
  geom_line() +
  geom_errorbar()

```

# bins
```{r}
data_bins <- objective_2_data %>%
  group_by(n_sesion) %>% 
  mutate(tiempo = tiempo - tiempo[1]) %>% 
  ungroup() %>% 
    group_by(
      ID,
      n_sesion
      ) %>%
    mutate(
      # variable timestamp contains time relative to the start of the session,
      # bins are calculated based on the 
      # length of the session
      bins = cut(
        tiempo,
        breaks = seq(0, 60 * 60 * 1e3, by = 10 * 60 * 1e3),
        labels = FALSE,
        include.lowest = TRUE))

bin_baseline <- data_bins %>% 
  filter(n_sesion <= 12, n_sesion >= 7) %>% 
  group_by(ID, bins, n_sesion, pool) %>% 
  summarise(
    basal_bin_licks = n()
  ) %>% 
  ungroup() %>% 
  group_by(ID, bins, pool) %>% 
  summarise(
    basal_licks = mean(basal_bin_licks)
  ) %>% 
  drop_na()

data_bins_baseline <- data_bins %>% 
  group_by(ID, n_sesion, exp_group, exp_phase, bins, pool) %>% 
  summarise(
    licks = n()
    ) %>% 
  left_join(bin_baseline) %>% 
  mutate(
    delta_licks = ((licks - basal_licks) / basal_licks) * 100
  )

bins_mdl <- lmer(
  data = data_bins_baseline %>% filter(exp_phase == "experimental"),
  delta_licks ~ exp_group * bins + n_sesion + (1 | ID) + (1 | pool)
)
summary(bins_mdl)

bins_mdl_data <- plot_model(bins_mdl, type = "pred",  terms = c("bins", "exp_group"))$data %>% as_tibble()

p6 <- bins_mdl_data %>% 
  mutate(group = if_else(group == "control", "Control", "Uncertainty")) %>% 
  ggplot(aes(
    x, predicted, color = group, fill = group
  )) +
  geom_ribbon(aes(
    ymin = conf.low,
    ymax = conf.high
  ), alpha = 0.1) +
  geom_line() +
  scale_color_manual(values = c("black", "#56B4E9")) +
  scale_fill_manual(values = c("black", "#56B4E9")) +
  ylab("%Δ number of licks") +
  xlab("10 minute bins") +
  scale_x_continuous(breaks=seq(0, 6, 1)) +
  labs(fill = "", color = "") + 
  theme_pubr()
ggsave("../images/extra5.png", p6, width = 6, height = 4)

plot_model(bins_mdl, type = "pred",  terms = c("bins", "exp_group")) +
  theme_pubr() +
  theme(legend.position = "right", legend.title = element_blank()) +
  scale_color_manual(labels = c("Control", "Uncertainty"), values = c("blue", "red")) +
  ggtitle("") +
  ylab("Model number of licks estimates") +
  xlab("Session time (m)")

# burst
data_burst <- objective_2_data %>% 
  group_by(n_sesion) %>% 
  mutate(interval = tiempo - lag(tiempo), timestamp = tiempo - lag(tiempo), group = exp_group) %>% 
  ungroup()

burst <- burst_analysis(data_burst, 500)

size_mdl_data <- burst %>% 
  filter(values == "in_cluster", cluster_length < 100) %>% 
  mutate(exp_phase = if_else(n_sesion > 12, "experimental", "baseline")) %>% 
  group_by(ID, n_sesion, exp_phase, group, pool) %>% 
  summarise(cluster_length_ = mean(cluster_length)) %>% 
  drop_na()

size_baseline <- size_mdl_data %>%
  filter(n_sesion <= 12, n_sesion >= 7) %>% 
  group_by(
    ID,
    n_sesion
  ) %>% 
  summarise(size_basal = mean(cluster_length_)) %>% 
  ungroup() %>% 
  group_by(ID) %>% 
  summarise(s_basal = mean(size_basal))

burst_mdl_data <- burst %>% 
  filter(values == "in_cluster") %>% 
  mutate(exp_phase = if_else(n_sesion > 12, "experimental", "baseline")) %>% 
  group_by(
    ID,
    pool,
    n_sesion,
    group,
    exp_phase
  ) %>% 
  summarise(
    n_cluster = n()
  )

burst_baseline <- burst_mdl_data %>%
  filter(n_sesion <= 12, n_sesion >= 7) %>% 
  group_by(
    ID,
    n_sesion
  ) %>% 
  summarise(burst_basal = mean(n_cluster)) %>% 
  ungroup() %>% 
  group_by(ID) %>% 
  summarise(b_basal = mean(burst_basal))

burst_mdl_data <- burst_mdl_data %>% 
  left_join(burst_baseline, by = c("ID"))

size_mdl_data <- size_mdl_data %>% 
  left_join(size_baseline, by = c("ID"))

burst_mdl <- lmer(
  data = burst_mdl_data,
  n_cluster ~ group * exp_phase + b_basal + (1 | ID) + (1 | pool)
)
summary(burst_mdl)

size_mdl <- lmer(
  data = size_mdl_data,
  cluster_length_ ~ group * exp_phase + s_basal + (1 | ID/pool)
)
summary(size_mdl)

burst_df <- plot_model(burst_mdl, type = "int")$data %>% as_tibble()
size_df <- plot_model(size_mdl, type = "int")$data %>% as_tibble()

p7 <- burst_df %>% 
  mutate(x = if_else(x == 1, "Basal", "Uncertainty")) %>% 
    ggplot(aes(group, predicted, fill = x, color = x)) +
    geom_col(position = "dodge2") +
    geom_errorbar(aes(
      ymin = conf.low, ymax = conf.high
    ), position = position_dodge(0.9), width = 0.3) +
    scale_fill_manual(values = c("black", "#56B4E9")) +
    scale_color_manual(values = c("black", "#56B4E9")) +
    theme_pubr() +
    ylab("Number of bursts (500 ms) estimates") +
    xlab("") +
    scale_x_discrete(labels = c("Control", "Uncertainty")) +
    labs(fill = "Experimental phase", color = "Experimental phase") + 
    geom_signif(
      y_position = c(150, 150), xmin = c(0.8, 1.8), xmax = c(1.2, 2.2),
      annotation = c("NS", "**"), tip_length = 0
    )
ggsave("../images/extra6.png", p7, width = 6, height = 4)

p8 <- size_df %>% 
  mutate(x = if_else(x == 1, "Basal", "Uncertainty")) %>% 
    ggplot(aes(group, predicted, fill = x, color = x)) +
    geom_col(position = "dodge2") +
    geom_errorbar(aes(
      ymin = conf.low, ymax = conf.high
    ), position = position_dodge(0.9), width = 0.3) +
    scale_fill_manual(values = c("black", "#56B4E9")) +
    scale_color_manual(values = c("black", "#56B4E9")) +
    theme_pubr() +
    ylab("Length of bursts (500 ms) estimates") +
    xlab("") +
    scale_x_discrete(labels = c("Control", "Uncertainty")) +
    labs(fill = "Experimental phase", color = "Experimental phase") + 
    geom_signif(
      y_position = c(12, 12), xmin = c(0.8, 1.8), xmax = c(1.2, 2.2),
      annotation = c("NS", "**"), tip_length = 0
    )
ggsave("../images/extra7.png", p8, width = 6, height = 4)

# number of clusters
burst_size <- burst %>% 
  mutate(
    exp_phase = if_else(n_sesion > 12, "EXPERIMENTAL", "BASAL")
    ) %>% 
  group_by(ID, n_sesion, group, exp_phase) %>% 
  filter(values == "in_cluster")

basal_cluster <- burst_size %>% 
  filter(exp_phase == "BASAL") %>% 
  group_by(ID) %>% 
  summarise(basal_cluster_size = mean(cluster_length_m)) %>% 
  select(ID, basal_cluster_size)

burst_size_basal <- burst_size %>% 
  left_join(basal_cluster, by = c("ID")) %>% 
  mutate(
    delta_length = cluster_length_m - basal_cluster_size
  )

mdl_burst <- lmer(
  data = burst_size,
  cluster_length ~ exp_phase * group +(1 | ID)
)
summary(mdl_burst)
emmeans::emmeans(mdl_burst, pairwise ~ exp_phase * group)
confint(burst_emm)

# percent
pref_perc <- data_pool1 %>% 
  group_by(ID, n_sesion, is_random, exp_phase, exp_group) %>% 
  summarise(
    licks = n()
  ) %>% 
  filter(exp_phase == "EXPERIMENTAL", exp_group == "UNC") %>% 
  pivot_wider(
    names_from = is_random,
    values_from = licks
  ) %>% 
  mutate(
    ratio = `TRUE` / (`TRUE` + `FALSE`) 
  ) %>% 
  ungroup() %>% 
  group_by(
    ID
  ) %>% 
  summarise(m = mean(ratio)) %>% 
  ungroup() %>% 
  summarise(mm = mean(m), s = sd(m) / sqrt(n()))

# plot percent
pref_plot <- data_pool1 %>% 
  group_by(ID, n_sesion, is_random, exp_phase, exp_group) %>% 
  summarise(
    licks = n()
  ) %>% 
  filter(exp_phase == "EXPERIMENTAL", exp_group == "UNC")

pref_plot %>% 
  mutate(is_random = if_else(is_random == FALSE, "Non-random", "Random"),
         exp_group = if_else(exp_group == "UNC", "Uncertainty", "Control")) %>% 
  group_by(n_sesion, is_random) %>% 
  summarise(
    m = mean(licks),
    s = sd(licks) / sqrt(n())
  ) %>% 
  ungroup() %>% 
  group_by(is_random) %>% 
  summarise(
    mm = mean(m),
    ss = sd(m) / sqrt(n())
  ) %>% 
  ggplot(aes(is_random,
             mm,
             ymax = mm + ss,
             ymin = mm - ss,
             fill = is_random)) +
  geom_col() +
  geom_errorbar(width = 0.3) +
  theme_pubr() +
  theme(legend.position = "none") +
  geom_signif(
    comparisons = list(c("Non-random", "Random")),
    map_signif_level = TRUE, annotations = c("*")
  ) +
  xlab("") +
  ylab("Mean number of licks")
ggsave("../images/figure6.png", width = 6, height = 4)

# lmer
mdl_bins <- lmer(
  data = data_bins_baseline %>%  filter(exp_phase == "EXPERIMENTAL"),
  delta_licks ~ exp_group * bins +(1 | ID)
)
summary(mdl_bins)
confint(mdl_bins)
plot_model(mdl_bins, type = "pred", terms = c("bins", "exp_group")) +
  theme_pubr() +
  theme(legend.position = "right", legend.title = element_blank()) +
  scale_color_manual(labels = c("Control", "Uncertainty"), values = c("blue", "red")) +
  ggtitle("") +
  ylab("Model number of licks estimates") +
  xlab("Session time (m)")
ggsave("../images/figure7.png", width = 6, height = 4)
```


This data sets correspond to experiments where one spout in the lickometer delivered rewards with a probability of 0.5 POOL 2

```{r}
# set working directory where this file is located
cur_dir <- dirname(getSourceEditorContext()$path)
setwd(cur_dir)

# load experiment
data_pool2 <- load_experiment(
  '../data/meta/lickometer_metadata.csv',
  '../data/raw/pool_2'
)
```
# plots
```{r}
ind <- data_raw %>% 
  mutate(
    sensor = if_else(sensor == 0, "Left", "Right") 
  ) %>% 
    group_by(
      ID,
      n_sesion,
      sensor
    ) %>% 
    summarise(
      licks = n(),
      events = max(evento)
    ) %>% 
    ungroup()

ind_pref <- ind %>% 
  pivot_wider(
    names_from = sensor,
    values_from = c("licks", "events")
  ) %>% 
  mutate(
    licks_ratio = licks_Left / licks_Right,
    events_ratio = events_Left / events_Right
  )
  
gr <- ind %>% 
    group_by(
      n_sesion,
      sensor
    ) %>% 
    summarise(
      err_licks = sd(licks) / sqrt(n()),
      err_events = sd(events) / sqrt(n()),
      licks = mean(licks),
      events = mean(events)
    )
  
p1 <- gr %>% 
    ggplot(aes(
      n_sesion,
      licks,
      color = as.factor(sensor),
      group = as.factor(sensor)
    )) +
    geom_line() +
    geom_point() +
    geom_errorbar(
      aes(
      ymin = licks - err_licks,
      ymax = licks + err_licks
      ),
      width = 0.3
    ) +
    geom_line(data = ind, aes(group = interaction(ID, sensor)), alpha = 0.3) +
    geom_point(data = ind, aes(group = interaction(ID, sensor)), alpha = 0.3)
p2 <- gr %>% 
    ggplot(aes(
      n_sesion,
      events,
      color = as.factor(sensor),
      group = as.factor(sensor)
    )) +
    geom_line() +
    geom_point() +
    geom_errorbar(
      aes(
      ymin = events - err_events,
      ymax = events + err_events
      ),
      width = 0.3
    ) +
    geom_line(data = ind, aes(group = interaction(ID, sensor)), alpha = 0.3) +
   geom_point(data = ind, aes(group = interaction(ID, sensor)), alpha = 0.3)
p3 <- ind_pref %>% 
  ggplot(aes(
    n_sesion,
    licks_ratio,
    color = ID,
    group = ID
  )) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0.5)
  
p1 <- p1 +
  ggtitle("Licks") +
  theme_pubr()
p2 <- p2 +
  ggtitle("Events") +
  theme_pubr()
p3 <- p3 +
  ggtitle("Spout preference") +
  theme_pubr()
plot_grid(p1, p2, p3, labels = c('A', 'B', 'C'), label_size = 12)
```

# POOL 2

```{r}
data_pool2 <- load_experiment(
  '../data/meta/lickometer_metadata.csv',
  '../data/raw/pool_2'
)

# add groups and experimental phase
data_pool2 <- data_pool2 %>% 
  mutate(
    exp_phase = if_else(as.numeric(n_sesion) >= 13, "experimental", "basal"),
    exp_group = if_else(ID %in% c(393, 394, 398, 400), "uncertainty", "control")
  )

data_pool1_mdl <- data_pool1 %>% 
  group_by(ID, n_sesion, exp_group, exp_phase) %>% 
  summarise(
    total_licks = n()
  )  %>% 
  mutate(
    n_sesion = as.numeric(n_sesion),
    exp_group = if_else(exp_group == "UNC", "uncertainty", "control"),
    exp_phase = if_else(exp_phase == "BASAL", "basal", "experimental")
    ) %>% 
  group_by(ID, n_sesion) %>% 
  arrange(n_sesion, by_group = TRUE) %>% 
  filter(n_sesion != 29) %>% 
  mutate(pool = 1)

data_pool2_mdl <- data_pool2 %>% 
  group_by(ID, n_sesion, exp_group, exp_phase) %>% 
  summarise(
    total_licks = n()
  ) %>% 
  mutate(n_sesion = as.numeric(n_sesion)) %>% 
  group_by(ID, n_sesion) %>% 
  arrange(n_sesion, by_group = TRUE) %>% 
  mutate(pool = 2)

pool_merge = bind_rows(data_pool1_mdl, data_pool2_mdl)

licks_mdl <- lmer(
  data = pool_merge,
  total_licks ~ exp_group * exp_phase * n_sesion + (1 | ID) + (1 | pool)
)
summary(licks_mdl)
```

