---
title: "thesis_data_analysis"
author: "Luis Luarte"
date: '2022-08-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load libs

```{r}
pacman::p_load(
  tidyverse,
  ggplot2,
  rstudioapi,
  devtools,
  lme4,
  lmerTest,
  googledrive,
  ggpubr,
  cowplot
)

# source lickometer library
devtools::source_url("https://github.com/lab-cpl/lickometer-library/blob/main/src/lickometer_functions_compilate.R?raw=TRUE")

```

# load data sets

POOL 1

```{r}
# this data is in a different format because it was done in a previous
# version of the lickometer
# change col names before merging both pools
data_pool1 <- readRDS('../data/objective_2_pool_1.RDS')
```

# stats pool 1

```{r}
# total number of licks
data_mdl_1 <- data_pool1 %>% 
  filter(n_sesion < 29) %>% 
  group_by(
    exp_group,
    exp_phase,
    ID,
    n_sesion
    ) %>% 
  summarise(
    licks = n(),
    events = max(eventsCum),
    rewards = max(rewardsCum),
    lr = licks / rewards
  )

basal_licks <- data_mdl_1 %>% 
  filter(exp_phase == "BASAL") %>% 
  group_by(
    ID
  ) %>% 
  summarise(
    basal_licks = mean(licks),
    basal_events = mean(events),
    basal_lr = mean(lr)
  )

data_delta <- data_mdl_1 %>% 
  left_join(basal_licks) %>% 
  mutate(
    delta_licks = ((licks - basal_licks) / basal_licks) * 100,
    delta_events = ((events - basal_events) / basal_events) * 100,
    delta_lr = ((lr - basal_lr) / basal_lr) * 100,
  )

mdl_1 <- lmer(
  data = data_delta %>%  filter(exp_phase == "EXPERIMENTAL"),
  delta_events ~ exp_group * n_sesion + (1 | ID)
)
summary(mdl_1)

data_mdl_1_m <- data_mdl_1 %>% 
  ungroup() %>% 
  group_by(
    exp_group,
    exp_phase,
    n_sesion
  ) %>% 
  summarise(
    m = mean(licks),
    s = sd(licks) / sqrt(n())
  )

data_mdl_1_m %>% 
  ggplot(aes(
    n_sesion,
    m,
    color = exp_group,
    ymax = m + s,
    ymin = m - s
  )) +
  geom_line() +
  geom_errorbar()

```


This data sets correspond to experiments where one spout in the lickomter delivered rewards with a probability of 0.5 POOL 2

```{r}
# set working directory where this file is located
cur_dir <- dirname(getSourceEditorContext()$path)
setwd(cur_dir)

# load experiment
data_pool2 <- load_experiment(
  '../data/meta/lickometer_metadata.csv',
  '../data/raw/pool_2/FR'
)
```
# plots
```{r}
ind <- data_raw %>% 
  mutate(
    sensor = if_else(sensor == 0, "Left", "Right") 
  ) %>% 
    group_by(
      ID,
      n_sesion,
      sensor
    ) %>% 
    summarise(
      licks = n(),
      events = max(evento)
    ) %>% 
    ungroup()

ind_pref <- ind %>% 
  pivot_wider(
    names_from = sensor,
    values_from = c("licks", "events")
  ) %>% 
  mutate(
    licks_ratio = licks_Left / licks_Right,
    events_ratio = events_Left / events_Right
  )
  
gr <- ind %>% 
    group_by(
      n_sesion,
      sensor
    ) %>% 
    summarise(
      err_licks = sd(licks) / sqrt(n()),
      err_events = sd(events) / sqrt(n()),
      licks = mean(licks),
      events = mean(events)
    )
  
p1 <- gr %>% 
    ggplot(aes(
      n_sesion,
      licks,
      color = as.factor(sensor),
      group = as.factor(sensor)
    )) +
    geom_line() +
    geom_point() +
    geom_errorbar(
      aes(
      ymin = licks - err_licks,
      ymax = licks + err_licks
      ),
      width = 0.3
    ) +
    geom_line(data = ind, aes(group = interaction(ID, sensor)), alpha = 0.3) +
    geom_point(data = ind, aes(group = interaction(ID, sensor)), alpha = 0.3)
p2 <- gr %>% 
    ggplot(aes(
      n_sesion,
      events,
      color = as.factor(sensor),
      group = as.factor(sensor)
    )) +
    geom_line() +
    geom_point() +
    geom_errorbar(
      aes(
      ymin = events - err_events,
      ymax = events + err_events
      ),
      width = 0.3
    ) +
    geom_line(data = ind, aes(group = interaction(ID, sensor)), alpha = 0.3) +
   geom_point(data = ind, aes(group = interaction(ID, sensor)), alpha = 0.3)
p3 <- ind_pref %>% 
  ggplot(aes(
    n_sesion,
    licks_ratio,
    color = ID,
    group = ID
  )) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0.5)
  
p1 <- p1 +
  ggtitle("Licks") +
  theme_pubr()
p2 <- p2 +
  ggtitle("Events") +
  theme_pubr()
p3 <- p3 +
  ggtitle("Spout preference") +
  theme_pubr()
plot_grid(p1, p2, p3, labels = c('A', 'B', 'C'), label_size = 12)
```

